### ISSUE TITLE
Support for monorepo and multiple tsconfig.json

### ISSUE THREAD

**Issue by WesleyYue** [d-kimuson/ts-type-expand#322]
Thanks for the great extension. Would be great if it can support monorepo setups like Yarn workspaces that has multiple tsconfigs across the different packages in the monorepo.

**Comment by d-kimuson** [comment]
@WesleyYue  Thank you for your request.

From #99 or later, which is currently under development, the extension will use the built-in LSP instead of the separate LSP for the extension. Thus, monorepo with multiple `tsconfig.json` will work as long as they are resolved by the built-in LSP.

Still beta, but you can try it from [ts-type-expand-beta - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=kimuson.ts-type-expand-beta)

**Comment by d-kimuson** [comment]
#99 has been merged and the setup of the case with multiple tsconfig.json from [ts-type-expand v1](https://marketplace.visualstudio.com/items?itemName=kimuson.ts-type-expand) is now supported.
Therefore, closed the issue.
