### ISSUE TITLE
Feature request: Volar takeover mode compatibility

### ISSUE THREAD

**Issue by brawaru** [d-kimuson/ts-type-expand#330]
Volar (extension for working with Vue) has a [takeover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) in which you disable built-in TypeScript extension and use Volar exclusively, which makes it more performant, because then only 1 language server needs to be created. Unfortunately, this makes it impossible to use this extension, because it depends on the built-in TypeScript extension. It would be great if both could work together, since theoretically Volar should be just an extended built-in language server (although I cannot tell for sure).

**Comment by d-kimuson** [comment]
Thanks for the feature request.
Currently, it doesn't support SFC in Vue, not only in takeover mode.

As you guessed, it seems possible to connect in principle, but there is a problem before that.
I am not familiar with the TS connectivity of SFC, but if the first line of the SFC script tag is selected in VSCode, it will be the 10th line, for example, because it is preceded by a template. However, the number of lines expected by tsserver is probably the first line, so there is an incompatibility.

A way to work around this must be provided on the volar side. Or, if not, it is necessary to implement it. The implementation itself is not difficult, since it should be enough to subtract the number of lines from the script tag, but in any case, it will take time.

Also, to support the takeover mode you described, it is necessary to be able to enable ts-type-expand's `language-feature-plugin` for tsserver from the ts-type-expand extension side.

ref: https://github.com/d-kimuson/ts-type-expand/blob/f00f8900b9d15689ef568bc1e6dab90c7a45aa0c/packages/ts-type-expand/src/extension.ts#L226~L245

If it is possible to simply replace `vscode.vue-language-feature` and call `configurePlugin`, it should not be difficult to support, but if this API is not exposed, it will be difficult to support on the ts-type-expand side.

In any case, I understand that there are use cases you want to use in SFC. I will investigate.

**Comment by d-kimuson** [comment]
@brawaru We’ve released a new version with added support for Vue.
https://github.com/d-kimuson/ts-type-expand/releases/tag/v1.2.0

**Comment by d-kimuson** [comment]
Close.
