### ISSUE TITLE
1.0.1 version not displaying anything

### ISSUE THREAD

**Issue by finnmerlett** [d-kimuson/ts-type-expand#341]
Can I start by saying I absolutely love this extension, and I can't believe I have only just found it! Super super useful stuff.

I wanted to let you know that the display of the type-tree doesn't seem to render at all in the new `1.x` version. I was able to use it just fine with the latest `0.x` version, so that's what I'll be using for now, but felt I should make a bug report.

I am on an Intel MacBook Pro (2019) running Monterey 12.6.3. When I try to load the updated extension I get the toast activation message saying it is ready to use, and the title of the sidebar section reads `TS TYPE EXPAND (ACTIVE)` but the section is completely blank no matter what files I open or what types I click on.

Let me know if you need any more details. Thanks for all your hard work!

**Comment by d-kimuson** [comment]
@finnmerlett Sorry for the delay in checking.
Thanks for the bug report! I appreciate it!

I am a regular user of M1 Mac, but I also own an Intel Mac, so I will try to reproduce the problem on that machine. If I can't reproduce the problem, I may ask you to submit the logs.

Also, I don't have much time to contribute these days, so it may take some time to solve the problem. I would appreciate it if you could continue to use `0.X` for now.

Thank you so much!

**Comment by d-kimuson** [comment]
@finnmerlett Thank you for your patience!

I have just released v1.0.5, which fixes the same problem (it becomes active but does not expand when selected).
However, I suspect that this is the same cause, since the fix seems to be the cause of what should probably be broken in 0.x as well.
I would appreciate it if you could try the latest v1.0.5 and comment on whether the problem continues to occur!

**Comment by finnmerlett** [comment]
Just checked it out and looks like it's working with the v1.0.5! Nice one, cheers
