### ISSUE TITLE
Add Copy Type Feature

### ISSUE THREAD

**Issue by jovermier** [d-kimuson/ts-type-expand#383]
Add a copy feature so that all the properties and sub-properties are copied to the clipboard.

I frequently work with generics and complex types. I would like the ability to copy the types so that I can more easily work with AI.

Copy could either copy only the expanded properties or copy all nested properties. I recommend having a setting to limit nested depth to prevent infinite loops for the 'all nested properties' option.

**Comment by EivindYN** [comment]
Where you able to find a solution to this problem? I would also really like this for my project

**Comment by d-kimuson** [comment]
@jovermier , @EivindYN 
Thank you for the feature request!
I have implemented this feature in a simplified form for trial use.
You can try from [v1.1.0](https://github.com/d-kimuson/ts-type-expand/releases/tag/v1.1.0).

Here are the limitations:

- It copies the expanded type of the selected item as a type alias.
- Due to structural costs, the feature to copy only expanded items is not currently supported.
- The depth of nesting for recursive types is set to a fixed value.

It might not be very stable, so please open a separate issue for any bug reports or additional feature requests!

**Comment by d-kimuson** [comment]
Close.
