### ISSUE TITLE
Error: Unexpected intrinsicName Error, [object Object]

### ISSUE THREAD

**Issue by Evertt** [d-kimuson/ts-type-expand#386]
I'm using this extension in a Deno project, not a Node project. Maybe that's relevant.
The error only appears when I position the cursor on anything I've imported from an external library.
All my imports of external libraries are done the Deno way, so they look like:

```js
import { xml2js as xml2pojo } from "https://deno.land/x/xml2js@1.0.0/mod.ts";
```

And they are cached locally by Deno.
When I hover over the line where I call the function, VSCode is able to show my the type definition of the function, so VSCode itself is not having any troubles:

<img width="970" alt="image" src="https://github.com/d-kimuson/ts-type-expand/assets/1267282/c7858e2c-4105-47da-912e-56a06a876337">

I am just unsatisfied that I can't see what the type of the 2nd function argument (`userOptions: Xml2JsOptions`) expands into without **cmd + click** on the function name to navigate to the source file. I was hoping this extension could fix that.

But when I position my cursor on the function name `xml2pojo` the extension shows nothing and the logs say:
```
Error: Unexpected intrinsicName Error, [object Object]
```

### Edit

I'm doing a little debugging and I think I have found some useful information. When I **cmd + click** to go to the source file of the imported `xml2js` library then this extension doesn't work in that file at all. It raises the error:
```
SourceFile not found: /https/deno.land/x/xml2js@1.0.0/xml2js.ts
```

So I'm just guessing this extension can't work with Deno because:

1. It doesn't know where Deno caches its imported libraries locally.
2. And it can't open up a typescript file from a web URL either.

Is that a fair assessment? Please I would super appreciate it if you could fix this.

**Comment by d-kimuson** [comment]
Thank you for reporting this issue and providing detailed information about the problem you encountered while using this extension in a Deno project.

You are correct that this extension was primarily designed with Node.js in mind, and currently, it does not support other platforms. While it might work seamlessly with bun, Deno has a different module resolution mechanism, which is causing the extension to fail in your project.

Supporting Deno would require collaboration with the Deno extension for VSCode, and given my limited experience with Deno's inner workings, it might be challenging for me to implement a solution quickly. However, based on the logs you provided, it seems that with a few modifications, it might be possible to add support for Deno.

I believe that supporting Deno would be a great addition to this extension, and I appreciate you bringing this to my attention. When time permits, I will investigate the issue further and attempt to implement the necessary changes.

Thank you once again for your valuable feedback and for taking the time to report this issue. Your contribution is much appreciated, and I will keep you updated on the progress of adding Deno support to the extension.

**Comment by d-kimuson** [comment]
@Evertt 
I took a look at the implementation of [vscode_deno](https://github.com/denoland/vscode_deno).

As an overview, it seems that by disabling most of the functionality of VSCode's standard tsserver and building a Language Server for deno, it supports deno's URI-based imports and performs type checking.

This extension depends on that tsserver is built and resolving types. This is because it receives type information from tsserver using tsserver's Language Server Plugin(with CompilerAPI). Since the deno Language Server only has the correct type information, it might be possible to support it if the Language Service Plugin is supported by deno. However, the following document states that it is not supported.
https://docs.deno.com/runtime/manual/advanced/typescript/faqs#why-dont-you-support-language-service-plugins-or-transformer-plugins

I apologize for piquing your interest, but it appears that supporting deno is difficult.

**Comment by Evertt** [comment]
Ah, that's too bad, but I understand.
